drop old postgresql (rpm key, repo, packages)
igloo-project/roles-postgresql pull request #1
Opened 2024-02-23 10:07 UTC by cfagno

2024-02-27 09:25 UTC, cfagno commented on tasks/main.yml
> +    - include_tasks: pgdg_clean_check.yml
A supprimer

2024-02-28 09:53 UTC, lalmeras requested changes

2024-02-28 09:53 UTC, lalmeras commented on tasks/main.yml
> +        loop_var: pgdg_clean_version
Ajouter une valeur par défaut (`[]`)

2024-03-14 14:24 UTC, lalmeras approved these changes

2024-03-14 14:24 UTC, merged